version: 0.2
# documentation: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
phases:
  install:
    runtime-versions:
      nodejs: 18
    on-failure: ABORT
    commands:
      - API_ZIP_KEY=$COMMIT_ID-api.zip
      - npm ci
  build:
    on-failure: ABORT
    commands:
      # Build the front-end and the back-end
      - npm run build
      # Push FE to S3 (variable is defined in the CodeBuild Environment settings)
      - aws s3 sync packages/client/build/ s3://$AWS_S3_BUCKET_NAME
      # Invalidate cloudfront caches to immediately serve the new front-end files (variable is defined in the CodeBuild Environment settings)
      - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRO --paths "/index.html" "/static/*"
      - mv node_modules packages/server
artifacts:
  type: zip
  base-directory: 'packages/server'
  files:
    - '**/*'
cache:
  paths:
    - node_modules