import React, { useState, useRef, useEffect } from 'react';
import { Helmet } from 'react-helmet-async';

// ─── Types ────────────────────────────────────────────────────────────────────

interface TypeLevel { label: string; size: number; weight: number; }
interface RadiusToken { label: string; value: number; }

interface Tokens {
  colors: {
    backgroundBase: string;
    textOnDark:     string;
    accent:         string;
    primary:        string;
    secondary:      string;
  };
  type: {
    fontFamily: string;
    levels: {
      brand:     TypeLevel;
      h1:        TypeLevel;
      h2:        TypeLevel;
      h3:        TypeLevel;
      h4:        TypeLevel;
      h5:        TypeLevel;
      h6:        TypeLevel;
      body:      TypeLevel;
      bodySmall: TypeLevel;
    };
  };
  radii: {
    tight:  RadiusToken;
    normal: RadiusToken;
    soft:   RadiusToken;
  };
}

// ─── Defaults ─────────────────────────────────────────────────────────────────

const DEFAULTS: Tokens = {
  colors: {
    backgroundBase: '#1E1E1E',
    textOnDark:     '#FFFFFF',
    accent:         '#E6BABA',
    primary:        '#FF4B01',
    secondary:      '#515151',
  },
  type: {
    fontFamily: 'Jura',
    levels: {
      brand:     { label: 'Brand',       size: 1.625,  weight: 700 },
      h1:        { label: 'H1',          size: 2.375,  weight: 400 },
      h2:        { label: 'H2',          size: 1.5,    weight: 600 },
      h3:        { label: 'H3',          size: 1.0,    weight: 700 },
      h4:        { label: 'H4',          size: 0.9375, weight: 700 },
      h5:        { label: 'H5',          size: 0.875,  weight: 700 },
      h6:        { label: 'H6',          size: 0.75,   weight: 700 },
      body:      { label: 'Body',        size: 1.0,    weight: 500 },
      bodySmall: { label: 'Body Small',  size: 0.875,  weight: 700 },
    },
  },
  radii: {
    tight:  { label: 'Tight',  value: 2  },
    normal: { label: 'Normal', value: 6  },
    soft:   { label: 'Soft',   value: 12 },
  },
};

// ─── Export generators ────────────────────────────────────────────────────────

const toSCSS = (t: Tokens): string => {
  const ff = `'${t.type.fontFamily}', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`;
  const l = t.type.levels;
  return [
    `// Generated by /design`,
    `// Paste into packages/client/src/styles/_variables.scss`,
    ``,
    `$color-accent:    ${t.colors.accent};`,
    `$color-primary:   ${t.colors.primary};`,
    `$color-secondary: ${t.colors.secondary};`,
    ``,
    `$font-family-base:     ${ff};`,
    `$headings-font-family: ${ff};`,
    `$font-weight-base:     ${l.body.weight};`,
    `$headings-line-height: 1.2;`,
    `$line-height-base:     1.6;`,
    ``,
    `$h1-font-size: ${l.h1.size}rem;`,
    `$h2-font-size: ${l.h2.size}rem;`,
    `$h3-font-size: ${l.h3.size}rem;`,
    `$h4-font-size: ${l.h4.size}rem;`,
    `$h5-font-size: ${l.h5.size}rem;`,
    `$h6-font-size: ${l.h6.size}rem;`,
    ``,
    `$border-radius:      ${(t.radii.normal.value / 16).toFixed(4)}rem;  // ${t.radii.normal.value}px`,
    `$border-radius-sm:   ${(t.radii.tight.value  / 16).toFixed(4)}rem;  // ${t.radii.tight.value}px`,
    `$border-radius-lg:   ${(t.radii.soft.value   / 16).toFixed(4)}rem;  // ${t.radii.soft.value}px`,
    `$border-radius-pill: 50rem;`,
    ``,
    `// — Color overrides — uncomment when ready —`,
    `// $body-bg:    ${t.colors.backgroundBase};`,
    `// $body-color: ${t.colors.textOnDark};`,
    `// $primary:    ${t.colors.primary};`,
    `// $secondary:  ${t.colors.secondary};`,
  ].join('\n');
};

const toJSON = (t: Tokens): string => {
  const ff = `'${t.type.fontFamily}', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`;
  const l = t.type.levels;
  return JSON.stringify({
    colors: {
      backgroundBase:  t.colors.backgroundBase,
      textOnDark:      t.colors.textOnDark,
      accentColor:     t.colors.accent,
      primaryAction:   t.colors.primary,
      secondaryAction: t.colors.secondary,
    },
    typography: Object.fromEntries(
      (Object.keys(l) as Array<keyof typeof l>).map(k => [k, {
        fontFamily: ff,
        fontWeight: l[k].weight,
        fontSize:   `${l[k].size}rem`,
      }])
    ),
    radius: {
      tight:  `${t.radii.tight.value}px`,
      normal: `${t.radii.normal.value}px`,
      soft:   `${t.radii.soft.value}px`,
    },
  }, null, 2);
};

// ─── Editor input styles ──────────────────────────────────────────────────────

const ei = {
  hex: {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 4,
    color: '#fff',
    fontFamily: 'ui-monospace, monospace',
    fontSize: 12,
    letterSpacing: '0.04em',
    outline: 'none',
    padding: '4px 8px',
    width: 90,
  } as React.CSSProperties,
  num: {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 4,
    color: '#fff',
    fontSize: 12,
    outline: 'none',
    padding: '4px 6px',
    textAlign: 'right' as const,
    width: 58,
  } as React.CSSProperties,
  sel: {
    background: '#1A1A1A',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 4,
    color: '#fff',
    cursor: 'pointer',
    fontSize: 12,
    outline: 'none',
    padding: '4px 4px',
  } as React.CSSProperties,
  label: {
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'ui-monospace, monospace',
    fontSize: 11,
  } as React.CSSProperties,
};

// ─── Editor sub-components ────────────────────────────────────────────────────

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div>
    <div style={{
      borderTop: '1px solid rgba(255,255,255,0.06)',
      color: 'rgba(255,255,255,0.28)',
      fontSize: 9,
      fontWeight: 700,
      letterSpacing: '0.14em',
      padding: '18px 20px 10px',
      textTransform: 'uppercase',
    }}>
      {title}
    </div>
    <div style={{ padding: '0 20px 14px' }}>{children}</div>
  </div>
);

const ColorRow: React.FC<{
  label: string;
  value: string;
  onChange: (v: string) => void;
}> = ({ label, value, onChange }) => {
  const pickerRef = useRef<HTMLInputElement>(null);
  const [draft, setDraft] = useState(value);
  useEffect(() => setDraft(value), [value]);
  return (
    <div style={{ alignItems: 'center', display: 'flex', gap: 8, padding: '4px 0' }}>
      <div
        role="button"
        title="Open color picker"
        onClick={() => pickerRef.current?.click()}
        style={{
          backgroundColor: value,
          border: '1px solid rgba(255,255,255,0.15)',
          borderRadius: 4,
          cursor: 'pointer',
          flexShrink: 0,
          height: 24,
          width: 24,
        }}
      />
      <input
        ref={pickerRef}
        type="color"
        value={value}
        onChange={e => { onChange(e.target.value); setDraft(e.target.value); }}
        style={{ height: 0, opacity: 0, pointerEvents: 'none', position: 'absolute', width: 0 }}
      />
      <input
        type="text"
        value={draft}
        onChange={e => {
          setDraft(e.target.value);
          if (/^#[0-9A-Fa-f]{6}$/.test(e.target.value)) onChange(e.target.value);
        }}
        style={ei.hex}
        spellCheck={false}
      />
      <span style={ei.label}>{label}</span>
    </div>
  );
};

const TypeRow: React.FC<{
  level: TypeLevel;
  fontFamily: string;
  onSize: (v: number) => void;
  onWeight: (v: number) => void;
}> = ({ level, fontFamily, onSize, onWeight }) => (
  <div style={{ alignItems: 'center', display: 'flex', gap: 6, padding: '3px 0' }}>
    <span style={{ ...ei.label, flexShrink: 0, width: 72 }}>{level.label}</span>
    <input
      type="number"
      value={level.size}
      step={0.0625}
      min={0.5}
      max={5}
      onChange={e => { const v = parseFloat(e.target.value); if (!isNaN(v)) onSize(v); }}
      style={ei.num}
    />
    <span style={{ ...ei.label, fontSize: 10, opacity: 0.5 }}>rem</span>
    <select
      value={level.weight}
      onChange={e => onWeight(parseInt(e.target.value))}
      style={ei.sel}
    >
      {[300, 400, 500, 600, 700, 800].map(w => <option key={w} value={w}>{w}</option>)}
    </select>
    <span style={{
      color: 'rgba(255,255,255,0.3)',
      flex: 1,
      fontFamily: `'${fontFamily}', sans-serif`,
      fontSize: `${Math.min(level.size, 1.1)}rem`,
      fontWeight: level.weight,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    }}>
      Aa
    </span>
  </div>
);

const RadiusRow: React.FC<{
  label: string;
  value: number;
  onChange: (v: number) => void;
}> = ({ label, value, onChange }) => (
  <div style={{ alignItems: 'center', display: 'flex', gap: 10, padding: '5px 0' }}>
    <span style={{ ...ei.label, flexShrink: 0, width: 48 }}>{label}</span>
    <input
      type="range"
      min={0}
      max={24}
      value={value}
      onChange={e => onChange(parseInt(e.target.value))}
      style={{ accentColor: '#E6BABA', flex: 1 }}
    />
    <span style={{ ...ei.label, textAlign: 'right', width: 30 }}>{value}px</span>
    <div style={{
      background: 'rgba(255,255,255,0.14)',
      border: '1px solid rgba(255,255,255,0.18)',
      borderRadius: value,
      flexShrink: 0,
      height: 22,
      width: 22,
    }} />
  </div>
);

// ─── Main component ───────────────────────────────────────────────────────────

export const DesignSystem: React.FC = () => {
  const [t, setT] = useState<Tokens>(DEFAULTS);
  const [copied, setCopied] = useState<'scss' | 'json' | null>(null);

  const setColor = (k: keyof Tokens['colors'], v: string) =>
    setT(p => ({ ...p, colors: { ...p.colors, [k]: v } }));

  const setLevel = (k: keyof Tokens['type']['levels'], f: 'size' | 'weight', v: number) =>
    setT(p => ({
      ...p,
      type: { ...p.type, levels: { ...p.type.levels, [k]: { ...p.type.levels[k], [f]: v } } },
    }));

  const setRadius = (k: keyof Tokens['radii'], v: number) =>
    setT(p => ({ ...p, radii: { ...p.radii, [k]: { ...p.radii[k], value: v } } }));

  const copy = (format: 'scss' | 'json') => {
    navigator.clipboard.writeText(format === 'scss' ? toSCSS(t) : toJSON(t)).then(() => {
      setCopied(format);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  const { backgroundBase, textOnDark, accent, primary, secondary } = t.colors;
  const l = t.type.levels;
  const r = t.radii;
  const ff = `'${t.type.fontFamily}', -apple-system, sans-serif`;
  const dim = 'rgba(255,255,255,0.45)';
  const rule = '1px solid rgba(255,255,255,0.09)';
  const fontUrl = `https://fonts.googleapis.com/css2?family=${t.type.fontFamily.replace(/ /g, '+')}:wght@300;400;500;600;700;800&display=swap`;

  // Badge style — shared between preview contexts
  const badgeStyle = (small?: boolean): React.CSSProperties => ({
    background: `${accent}1A`,
    border: `1px solid ${accent}`,
    borderRadius: r.soft.value,
    color: accent,
    fontFamily: ff,
    fontSize: small ? `${l.bodySmall.size}rem` : `${l.bodySmall.size}rem`,
    fontWeight: l.bodySmall.weight,
    padding: '4px 10px',
    whiteSpace: 'nowrap',
  });

  return (
    <>
      <Helmet>
        <link href={fontUrl} rel="stylesheet" />
        <title>Design Tokens · Just Read Comics</title>
      </Helmet>

      <div style={{ display: 'flex', fontFamily: ff, height: '100vh', overflow: 'hidden' }}>

        {/* ── PREVIEW PANE ─────────────────────────────────────────────────── */}
        <div style={{ background: backgroundBase, color: textOnDark, flex: 1, overflowY: 'auto', padding: '40px 52px' }}>

          {/* —— Header mockup */}
          <div style={{ alignItems: 'center', borderBottom: rule, display: 'flex', justifyContent: 'space-between', marginBottom: 40, paddingBottom: 16 }}>
            <div style={{ alignItems: 'center', display: 'flex', gap: 10 }}>
              <div style={{ background: 'rgba(255,255,255,0.12)', borderRadius: r.tight.value, flexShrink: 0, height: 24, width: 24 }} />
              <span style={{ fontFamily: ff, fontSize: `${l.brand.size}rem`, fontWeight: l.brand.weight, letterSpacing: '0.03em' }}>
                just read comics
              </span>
            </div>
            <span style={{
              border: rule,
              borderRadius: r.normal.value,
              color: dim,
              fontFamily: ff,
              fontSize: `${l.bodySmall.size}rem`,
              fontWeight: l.bodySmall.weight,
              padding: '6px 16px',
            }}>
              Search series...
            </span>
          </div>

          {/* —— Series page layout */}
          <div style={{ display: 'grid', gap: 36, gridTemplateColumns: '180px 1fr' }}>

            {/* Cover image placeholder */}
            <div style={{
              aspectRatio: '2/3',
              background: 'rgba(255,255,255,0.06)',
              border: rule,
              borderRadius: r.normal.value,
            }} />

            {/* Detail column */}
            <div>
              <span style={{ display: 'block', fontFamily: ff, fontSize: `${l.h1.size}rem`, fontWeight: l.h1.weight, lineHeight: 1.15, marginBottom: 14 }}>
                Star Wars Shadows of the Empire
              </span>
              <p style={{ color: dim, fontFamily: ff, fontSize: `${l.body.size}rem`, fontWeight: l.body.weight, lineHeight: 1.65, margin: '0 0 28px', maxWidth: 420 }}>
                Tony Chu is a cop with a secret. A weird secret. He is cibopathic,
                which means he gets psychic impressions from whatever he eats.
              </p>

              <span style={{ display: 'block', fontFamily: ff, fontSize: `${l.h2.size}rem`, fontWeight: l.h2.weight, marginBottom: 4 }}>
                Available on:
              </span>

              {[
                { cat: 'Subscription',    count: 4 },
                { cat: 'Purchase',        count: 2 },
                { cat: 'Publisher / Other', count: 2 },
              ].map(({ cat, count }) => (
                <div key={cat} style={{ borderTop: rule, padding: '12px 0' }}>
                  <span style={{ display: 'block', fontFamily: ff, fontSize: `${l.h3.size}rem`, fontWeight: l.h3.weight, marginBottom: 10 }}>
                    {cat}
                  </span>
                  <div style={{ display: 'flex', gap: 8 }}>
                    {Array.from({ length: count }).map((_, i) => (
                      <div key={i} style={{
                        background: 'rgba(255,255,255,0.09)',
                        borderRadius: r.normal.value,
                        height: 44,
                        width: 44,
                      }} />
                    ))}
                  </div>
                </div>
              ))}

              <div style={{ borderTop: rule, padding: '12px 0' }}>
                <span style={{ display: 'block', fontFamily: ff, fontSize: `${l.h3.size}rem`, fontWeight: l.h3.weight, marginBottom: 10 }}>
                  Creators:
                </span>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                  {['Writer Name', 'Artist Name', 'Colorist'].map(name => (
                    <span key={name} style={badgeStyle()}>
                      {name}
                    </span>
                  ))}
                </div>
              </div>

              <div style={{ display: 'flex', gap: 10, marginTop: 20 }}>
                <button style={{
                  background: secondary,
                  border: 'none',
                  borderRadius: r.normal.value,
                  color: textOnDark,
                  cursor: 'pointer',
                  fontFamily: ff,
                  fontSize: `${l.bodySmall.size}rem`,
                  fontWeight: l.bodySmall.weight,
                  padding: '9px 22px',
                }}>
                  Suggest Edit
                </button>
                <button style={{
                  background: primary,
                  border: 'none',
                  borderRadius: r.normal.value,
                  color: '#fff',
                  cursor: 'pointer',
                  fontFamily: ff,
                  fontSize: `${l.bodySmall.size}rem`,
                  fontWeight: l.bodySmall.weight,
                  padding: '9px 22px',
                }}>
                  Visit Series
                </button>
              </div>
            </div>
          </div>

          {/* —— Divider */}
          <div style={{ borderTop: rule, margin: '48px 0 40px' }} />

          {/* —— Type scale reference */}
          <div style={{ color: 'rgba(255,255,255,0.25)', fontSize: 9, fontWeight: 700, letterSpacing: '0.14em', marginBottom: 28, textTransform: 'uppercase' }}>
            Type scale
          </div>
          <div style={{ display: 'grid', gap: 14 }}>
            {(Object.keys(l) as Array<keyof typeof l>).map(k => (
              <div key={k} style={{ alignItems: 'baseline', display: 'flex', gap: 16 }}>
                <span style={{ fontFamily: ff, fontSize: `${l[k].size}rem`, fontWeight: l[k].weight, lineHeight: 1.2 }}>
                  {l[k].label}
                </span>
                <span style={{ color: 'rgba(255,255,255,0.22)', fontFamily: 'ui-monospace, monospace', fontSize: 10, whiteSpace: 'nowrap' }}>
                  {l[k].size}rem / {l[k].weight}
                </span>
              </div>
            ))}
            <div style={{ alignItems: 'center', display: 'flex', gap: 10, marginTop: 4 }}>
              <span style={badgeStyle()}>Creator tag</span>
              <span style={{ color: 'rgba(255,255,255,0.22)', fontFamily: 'ui-monospace, monospace', fontSize: 10 }}>
                Body Small · accent border · {r.soft.value}px radius
              </span>
            </div>
          </div>

          {/* —— Divider */}
          <div style={{ borderTop: rule, margin: '48px 0 40px' }} />

          {/* —— Color + Radius tokens */}
          <div style={{ color: 'rgba(255,255,255,0.25)', fontSize: 9, fontWeight: 700, letterSpacing: '0.14em', marginBottom: 28, textTransform: 'uppercase' }}>
            Color tokens
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 20, marginBottom: 48 }}>
            {(Object.entries(t.colors) as [keyof Tokens['colors'], string][]).map(([k, v]) => (
              <div key={k}>
                <div style={{
                  background: v,
                  border: rule,
                  borderRadius: r.normal.value,
                  height: 64,
                  marginBottom: 8,
                  width: 64,
                }} />
                <div style={{ color: 'rgba(255,255,255,0.55)', fontFamily: 'ui-monospace, monospace', fontSize: 10 }}>{v}</div>
                <div style={{ color: 'rgba(255,255,255,0.3)', fontSize: 10 }}>{k}</div>
              </div>
            ))}
          </div>

          <div style={{ color: 'rgba(255,255,255,0.25)', fontSize: 9, fontWeight: 700, letterSpacing: '0.14em', marginBottom: 28, textTransform: 'uppercase' }}>
            Radius tokens
          </div>
          <div style={{ alignItems: 'flex-end', display: 'flex', gap: 28 }}>
            {(Object.keys(r) as Array<keyof typeof r>).map(k => (
              <div key={k}>
                <div style={{
                  background: accent,
                  borderRadius: r[k].value,
                  height: 72,
                  marginBottom: 10,
                  opacity: 0.75,
                  width: 72,
                }} />
                <div style={{ fontSize: 12, fontWeight: 600 }}>{r[k].label}</div>
                <div style={{ color: 'rgba(255,255,255,0.35)', fontFamily: 'ui-monospace, monospace', fontSize: 10 }}>
                  {r[k].value}px
                </div>
              </div>
            ))}
          </div>

          <div style={{ height: 60 }} />
        </div>

        {/* ── EDITOR SIDEBAR ───────────────────────────────────────────────── */}
        <div style={{
          background: '#141414',
          borderLeft: '1px solid rgba(255,255,255,0.07)',
          color: '#fff',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          width: 300,
        }}>

          {/* Sidebar header */}
          <div style={{ borderBottom: '1px solid rgba(255,255,255,0.07)', flexShrink: 0, padding: '14px 20px' }}>
            <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 2 }}>Design Tokens</div>
            <div style={{ color: 'rgba(255,255,255,0.3)', fontSize: 11 }}>just read comics</div>
          </div>

          {/* Scrollable controls */}
          <div style={{ flex: 1, overflowY: 'auto' }}>

            <Section title="Colors">
              <ColorRow label="Background"   value={t.colors.backgroundBase} onChange={v => setColor('backgroundBase', v)} />
              <ColorRow label="Text"         value={t.colors.textOnDark}     onChange={v => setColor('textOnDark', v)} />
              <ColorRow label="Accent"       value={t.colors.accent}         onChange={v => setColor('accent', v)} />
              <ColorRow label="Primary"      value={t.colors.primary}        onChange={v => setColor('primary', v)} />
              <ColorRow label="Secondary"    value={t.colors.secondary}      onChange={v => setColor('secondary', v)} />
            </Section>

            <Section title="Typography">
              <div style={{ alignItems: 'center', borderBottom: '1px solid rgba(255,255,255,0.06)', display: 'flex', gap: 8, marginBottom: 10, paddingBottom: 10 }}>
                <span style={{ ...ei.label, flexShrink: 0 }}>Font family</span>
                <input
                  type="text"
                  value={t.type.fontFamily}
                  onChange={e => setT(p => ({ ...p, type: { ...p.type, fontFamily: e.target.value } }))}
                  style={{ ...ei.hex, flex: 1, letterSpacing: 0, width: 'auto' }}
                  placeholder="Google Font name"
                />
              </div>
              {(Object.keys(l) as Array<keyof typeof l>).map(k => (
                <TypeRow
                  key={k}
                  level={l[k]}
                  fontFamily={t.type.fontFamily}
                  onSize={v  => setLevel(k, 'size',   v)}
                  onWeight={v => setLevel(k, 'weight', v)}
                />
              ))}
            </Section>

            <Section title="Border Radius">
              {(Object.keys(r) as Array<keyof typeof r>).map(k => (
                <RadiusRow
                  key={k}
                  label={r[k].label}
                  value={r[k].value}
                  onChange={v => setRadius(k, v)}
                />
              ))}
            </Section>

          </div>

          {/* Footer: export actions */}
          <div style={{ borderTop: '1px solid rgba(255,255,255,0.07)', display: 'flex', flexShrink: 0, gap: 8, padding: '12px 20px' }}>
            <button
              onClick={() => setT(DEFAULTS)}
              style={{
                background: 'transparent',
                border: '1px solid rgba(255,255,255,0.12)',
                borderRadius: 4,
                color: 'rgba(255,255,255,0.5)',
                cursor: 'pointer',
                flex: 1,
                fontSize: 11,
                padding: '7px 0',
              }}
            >
              Reset
            </button>
            <button
              onClick={() => copy('json')}
              style={{
                background: copied === 'json' ? 'rgba(100,200,100,0.15)' : 'rgba(255,255,255,0.06)',
                border: `1px solid ${copied === 'json' ? 'rgba(100,200,100,0.4)' : 'rgba(255,255,255,0.12)'}`,
                borderRadius: 4,
                color: copied === 'json' ? '#7dcc7d' : 'rgba(255,255,255,0.6)',
                cursor: 'pointer',
                flex: 1.2,
                fontSize: 11,
                padding: '7px 0',
                transition: 'all 0.15s',
              }}
            >
              {copied === 'json' ? '✓ Copied' : 'Copy JSON'}
            </button>
            <button
              onClick={() => copy('scss')}
              style={{
                background: copied === 'scss' ? 'rgba(100,200,100,0.2)' : t.colors.primary,
                border: 'none',
                borderRadius: 4,
                color: '#fff',
                cursor: 'pointer',
                flex: 1.2,
                fontSize: 11,
                fontWeight: 600,
                padding: '7px 0',
                transition: 'background 0.15s',
              }}
            >
              {copied === 'scss' ? '✓ Copied' : 'Copy SCSS'}
            </button>
          </div>

        </div>
      </div>
    </>
  );
};
